In [45]:
import pandas as pd
import numpy as np

In [36]:
data = 'BTC-market-analysis_2021-25.csv'
df = pd.read_csv(data)
df.head()

,date,adj close,close,high,low,open,volume,sp500_close,gold_close,dxy_close,...,google_trends_score,btc_return,btc_log_return,sp500_return,gold_return,dxy_return,btc_vol_7d,btc_vol_14d,target_return,target_direction
0,2021-01-11,35566.656250,35566.656250,38346.531250,30549.599609,38346.531250,123320567399,3799.610107,1849.599976,90.540001,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.089979,0
1,2021-01-12,33922.960938,33922.960938,36568.527344,32697.976562,35516.359375,74773277909,3801.189941,1842.900024,90.050003,...,NaN,-0.046215,-0.047316,0.000416,-0.003622,-0.005412,NaN,NaN,-0.039888,0
2,2021-01-13,37316.359375,37316.359375,37599.960938,32584.667969,33915.121094,69364315979,3809.840088,1853.599976,90.320000,...,NaN,0.100032,0.095340,0.002276,0.005806,0.002998,NaN,NaN,-0.184472,0
3,2021-01-14,39187.328125,39187.328125,39966.406250,36868.562500,37325.109375,63615990033,3795.540039,1850.300049,90.239998,...,NaN,0.050138,0.048922,-0.003753,-0.001780,-0.000886,NaN,NaN,-0.145997,0
4,2021-01-15,36825.367188,36825.367188,39577.710938,34659.589844,39156.707031,67760757881,3768.250000,1829.300049,90.779999,...,NaN,-0.060274,-0.062166,-0.007190,-0.011350,0.005984,NaN,NaN,-0.068132,0

In [ ]:
df.columns

Index(['date', 'adj close', 'close', 'high', 'low', 'open', 'volume',
       'sp500_close', 'gold_close', 'dxy_close', 'fng_score', 'hash_rate',
       'google_trends_score', 'btc_return', 'btc_log_return', 'sp500_return',
       'gold_return', 'dxy_return', 'btc_vol_7d', 'btc_vol_14d',
       'target_return', 'target_direction'],
      dtype='str')

In [26]:
df[['open', 'high', 'low', 'close']]

              open          high           low         close
0     38346.531250  38346.531250  30549.599609  35566.656250
1     35516.359375  36568.527344  32697.976562  33922.960938
2     33915.121094  37599.960938  32584.667969  37316.359375
3     37325.109375  39966.406250  36868.562500  39187.328125
4     39156.707031  39577.710938  34659.589844  36825.367188
...            ...           ...           ...           ...
1821  93876.945312  94395.296875  91286.546875  93729.031250
1822  93727.468750  93738.789062  90601.804688  91308.054688
1823  91309.640625  91485.851562  89233.875000  91027.125000
1824  91026.273438  91910.671875  89625.382812  90513.101562
1825  90517.796875  90642.140625  90317.218750  90415.554688

[1826 rows x 4 columns]

In [39]:
df[['btc_vol_7d', 'btc_vol_14d']]

      btc_vol_7d  btc_vol_14d
0            NaN          NaN
1            NaN          NaN
2            NaN          NaN
3            NaN          NaN
4            NaN          NaN
...          ...          ...
1821    0.011982     0.010156
1822    0.016560     0.013097
1823    0.016481     0.013048
1824    0.016161     0.013248
1825    0.015925     0.013251

[1826 rows x 2 columns]

In [40]:
df.isnull().sum()

date                    0
adj close               0
close                   0
high                    0
low                     0
open                    0
volume                  0
sp500_close             0
gold_close              0
dxy_close               0
fng_score               0
hash_rate               0
google_trends_score     6
btc_return              1
btc_log_return          1
sp500_return            1
gold_return             1
dxy_return              1
btc_vol_7d              7
btc_vol_14d            14
target_return          14
target_direction        0
dtype: int64

In [41]:
# df.dropna(inplace = True)

In [51]:
df['target_log_return'] = df['btc_log_return'].shift(-14).rolling(window=14).sum()

In [ ]:
df['xau_log_return'] = np.log(df['gold_return'].shift(-14).rolling(window=14).sum() / df['close'])

/home/andreneves/Documentos/ML_Projects/.venv/lib/python3.13/site-packages/pandas/core/arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [56]:
df['xau_log_return'] = df['gold_return'].shift(-14).rolling(window=14).sum()
df['xau_log_return']
df['xau_log_return'].iloc[14]

np.float64(-0.0118628685686666)